using UnrealSharp.Utils.Extensions.IO;

namespace UnrealSharpTool.Core.CodeGen;

/// <summary>
/// Class CodegenCopyright.
/// </summary>
public static class CodegenCopyright
{
    /// <summary>
    /// Gets the copyright.
    /// </summary>
    /// <param name="filePath">The file path.</param>
    /// <returns>System.String.</returns>
    public static string GetCopyright(string filePath)
    {
        var text =
            "// ReSharper disable CommentTypo\n" +
            "// ***********************************************************************\n" +
            // ReSharper disable once StringLiteralTypo
            "// Author           : bodong\n" +
            "// ***********************************************************************\n" +
            $"// <copyright file=\"{filePath.GetFileName()}\">\n" +
            "//     Copyright (c) 2024 UnrealSharp. \n" +
            "// <summary>\n" +
            "// This code file is automatically generated by UnrealSharpTool. \n" +
            "// Manually modifying this file will lose the modifications at the next generate time. \n" +
            "// </summary>\n" +
            "// ***********************************************************************";

        return text;
    }

    /// <summary>
    /// Gets the unreal sharp copyright.
    /// </summary>
    /// <returns>System.String.</returns>
    public static string GetUnrealSharpCopyright()
    {
        const string text = "/*\n    MIT License\n\n    Copyright (c) 2024 UnrealSharp\n\n    Permission is hereby granted, free of charge, to any person obtaining a copy\n    of this software and associated documentation files (the \"Software\"), to deal\n    in the Software without restriction, including without limitation the rights\n    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n    copies of the Software, and to permit persons to whom the Software is\n    furnished to do so, subject to the following conditions:\n\n    The above copyright notice and this permission notice shall be included in all\n    copies or substantial portions of the Software.\n\n    THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\n    SOFTWARE.\n\n    Project URL: https://github.com/bodong1987/UnrealSharp\n*/";

        return text;
    }
}